release-date = "2022-03-01"

[[entries]]
id = "8ba4ee02-cef7-4bcd-9c27-898db5db4b99"
type = "improvement"
description = "improve replacing escaped Novella tags in `MarkdownPreprocessorAction`"
author = "@NiklasRosenstein"

[[entries]]
id = "d032e462-6c9a-4fc5-88d3-2c73c5b793d6"
type = "hygiene"
description = "`MkdocsTemplate` no longer stores actions it creates a members, you should access them using `NovellaContext.action()`"
author = "@NiklasRosenstein"
