[[entries]]
id = "d90ddf7c-fef9-4e71-88ba-8dc3c64e5d34"
type = "fix"
description = "Add an `update_with` function to the `MarkdownPreprocessor` action"
author = "@mgor"

[[entries]]
id = "d895daec-f21b-43d0-ab41-3867c34282d8"
type = "fix"
description = "Fix that Novella now also checks for `mkdocs.yaml`, not only `mkdocs.yml`"
author = "@mgor"

[[entries]]
id = "ff314fa4-b753-4671-b77b-70465b45667c"
type = "feature"
description = "Fix `name` parameter for `@anchor` tag."
author = "@mgor"
