[[entries]]
id = "1de26a7b-2571-48c2-b2fe-f70020ac07b7"
type = "feature"
description = "add `MkdocsConfigUpdateAction.profile` option and the `readthedocs` profile in addition to the default `material` profile"
author = "@NiklasRosenstein"

[[entries]]
id = "5e2c5bf9-263d-4a12-a4ba-37a5c87e8940"
type = "fix"
description = "Fix error when path that does not exist is passed to `NovellaBuilder.watch()`"
author = "@NiklasRosenstein"

[[entries]]
id = "6038ef3d-46b9-4b4e-8fea-f788a99817ac"
type = "improvement"
description = "Pause process currently running through a `RunAction` if it supports internal reloading while the pipeline is being re-executed"
author = "@NiklasRosenstein"

[[entries]]
id = "a9084d2b-7754-4de8-be11-fb4bd6965e31"
type = "improvement"
description = "reloads triggered by filesystem events are now handled in a separate thread to make sure that the event handling is not blocked"
author = "@NiklasRosenstein"
