[[entries]]
id = "fa61e257-0f69-4803-ba96-fe796390b025"
type = "fix"
description = "`@anchor` now only specifies the URL fragment if the link target is in the same page"
author = "@NiklasRosenstein"

[[entries]]
id = "6ac417b2-48d6-4877-b3a7-9cb6edef7493"
type = "improvement"
description = "options are now added to their own argument group if registered by a template"
author = "@NiklasRosenstein"
