[[entries]]
id = "2780b4cf-5e57-4dda-bb21-253030448fc8"
type = "improvement"
description = "sluggify anchor HTML ID for the @anchor flavor provided by the `mkdocs` template using `markdown.extensions.toc.slugify()`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/novella/issues/3",
]

[[entries]]
id = "41bee5ef-220b-4fd8-8018-c727aa4f2811"
type = "feature"
description = "add `--intercept` and `--intercept-log` options to CLI"
author = "@NiklasRosenstein"

[[entries]]
id = "5a4c3aa1-1dbe-4c45-b84a-d87f4f24dd45"
type = "breaking change"
description = "Split up responsibilities of `Novella` class between `Novella`, `NovellaContext` and `BuildContext`"
author = "@NiklasRosenstein"

[[entries]]
id = "2f3be16c-12e8-4474-80d4-6e30832b9760"
type = "feature"
description = "add `-r, --use-reloader` option to CLI"
author = "@NiklasRosenstein"

[[entries]]
id = "5b7568e2-dac6-4bd4-be5d-70079d9c50c9"
type = "feature"
description = "add `--dot` option to CLI"
author = "@NiklasRosenstein"

[[entries]]
id = "c3702d55-65c7-4b50-ac08-3db12b024005"
type = "feature"
description = "add `-c,--config-file` option"
author = "@NiklasRosenstein"

[[entries]]
id = "f8825dca-1b7d-4d24-8d18-eff2f4ab58eb"
type = "fix"
description = "fix `-h,--help` when no Novella build script is available in the current directory"
author = "@NiklasRosenstein"

[[entries]]
id = "d6ef6d01-a301-41fe-8d18-ad27261cef58"
type = "hygiene"
description = "cleanup build logic"
author = "@NiklasRosenstein"
