[[entries]]
id = "2780b4cf-5e57-4dda-bb21-253030448fc8"
type = "improvement"
description = "sluggify anchor HTML ID for the @anchor flavor provided by the `mkdocs` template using `markdown.extensions.toc.slugify()`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/novella/issues/3",
]

[[entries]]
id = "41bee5ef-220b-4fd8-8018-c727aa4f2811"
type = "feature"
description = "add `--intercept` and `--intercept-log` options to CLI"
author = "@NiklasRosenstein"
