[[entries]]
id = "ff383d15-2f92-43c0-bf78-9f8be3e2939d"
type = "improvement"
description = "add `novella.graph` module, `Action` is no a subclass of `novella.graph.Node`"
author = "@NiklasRosenstein"

[[entries]]
id = "45386b42-4a46-4f06-b991-d02b04e5c083"
type = "improvement"
description = "`NovellaContext.options` now throws an `AssertionError` if accessed before `NovellaContext.configure()` is called"
author = "@NiklasRosenstein"

[[entries]]
id = "eb854aaa-f48a-49ec-a72a-588d124d5d09"
type = "improvement"
description = "`MarkdownProcessorAction` now stores processors internally in a graph as well, and `MarkdownProcessor` is now a subclass of `novella.graph.Node`. This allows processors to express dependencies on other processors."
author = "@NiklasRosenstein"

[[entries]]
id = "a56474c4-4c17-4fd2-8edb-9e89f0daf6b7"
type = "improvement"
description = "`@cat` preprocessor now repeats preprocessing on the included content before injecting it"
author = "@NiklasRosenstein"

[[entries]]
id = "2c461f36-7aab-4de5-9f81-6f2f776d66f0"
type = "breaking change"
description = "remove `AnchorAndLinkRenderer` interface and use `MarkdownFlavor` instead, remove `Link` class and add `always_render_anchor_elements` option to `AnchorTagPreprocessor`. `MarkdownPreprocessorAction` now sets up `@shell`, `@cat` and `@anchor` by default. Add `MarkdownPreprocessor.setup()`"
author = "@NiklasRosenstein"
