[[entries]]
id = "e5331252-dbd3-4115-8c9a-f5617c2dca56"
type = "breaking change"
description = "rename `MkdocsTemplate.apply_default_config` to `~.apply_config`, make adding of `mkdocs-update-config` action unconditional and allow updating the MkDocs site name seperate from applying the default config"
author = "@NiklasRosenstein"
