name: "Python"

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install --no-venv-check -vv
    - run: slap test --no-venv-check
    - run: slap install --no-venv-check --only-extras docs && slap run --no-venv-check docs:build
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/develop' and '${{ matrix.python-version }}' == '3.10'
      with: { name: docs, path: docs/_site }

  publish-docs:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with: { name: docs, path: docs/_site }
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with: { branch: gh-pages, folder: docs/_site, ssh-key: "${{ secrets.DEPLOY_KEY }}" }
