# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.x"]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }

    - name: Install tooling
      run: pip install pipx -q && pipx install $(cat .github/files/slam-cli.txt)

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }

    - name: Install dependencies
      run: slam install --no-venv-check -vv

    - name: Run tests
      run: slam test

    - name: Build documentation
      run: cd docs && novella

    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/develop' and '${{ matrix.python-version }}' == '3.10'
      with:
        name: docs
        path: docs/_site

  publish-docs:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: docs

    - name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
