# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install --no-venv-check -vv
    - run: slap test
    - run: slap install --no-venv-check --only-extras docs && slap run docs:build
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/develop' and '${{ matrix.python-version }}' == '3.10'
      with: { name: docs, path: docs/_site }

  publish-docs:
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with: { name: docs, path: docs/_site }
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with: { branch: gh-pages, folder: docs/_site, ssh-key: "${{ secrets.DEPLOY_KEY }}" }
